arr-ai/arrai

- go.mod
- go.sum
- syntax/parse.go
- syntax/parse_value_test.go
> fix emptyset and arrays with new grammar

- syntax/parse.go
- syntax/parse_expr_test.go
> Fix parse nest

- syntax/parse.go
- syntax/parse_value_test.go
> Fix parse empty tuple

- rel/value.go
- rel/value_set.go
- rel/value_set_str.go
- rel/value_set_test.go
- syntax/str_stdlib.go
- syntax/str_stdlib_test.go
Add AsString() to Set interface which converts any Set to the internal String struct
Fixes #36
> Add AsString() to Set

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
- Add bug_report and feature_request issue templates
- Add PR template
> Add issue and PR templates

- cmd/arrai/eval.go
- cmd/arrai/main.go
- cmd/arrai/run.go
- cmd/arrai/run_test.go
- examples/hasbang/app
- add `run` to the command line which can evaluate an arrai file
Checklist:
> add run command

- .github/workflows/go.yml
- rel/astnode_value.go
- rel/astnode_value_test.go
- rel/value_set_test.go
- syntax/parse.go
- syntax/parse_value_test.go
- syntax/std.go
- syntax/test_helpers.go
- Add golangci-lint to CI
- Add multi-platform go test to CI
- Add coverage report to CI
> Add go lint, test and coverage report to CI workflow

- engine/engine.go
- syntax/import.go
- syntax/import_cache.go
Fixes #66  .
- Add cache for import behavior
- 
Checklist:
> #66 Add cache for local file import.

- rel/ops_set.go
- rel/value_set_generic.go
- rel/value_set_str.go
- syntax/expr_set_test.go
- Fix a bug enumerating strings with offsets
Checklist:
> Fix string enum bug

- cmd/arrai/json.go
Print JSON import results as valid arr.ai syntax.
> Fix JSON import printing

- Makefile
- rel/test_helpers.go
- syntax/import.go
- syntax/import_cache.go
- syntax/import_cache_test.go
- syntax/package_test.go
Speeds up testing by parallelising tests that connect to github.
> Parallelise tests requiring remote connectivity

- docs/std-encoding-json.md
- docs/std.md
- syntax/std.go
- syntax/std_encoding.go
- syntax/std_encoding_json.go
- syntax/std_encoding_json_test.go
> Move //.json to //.encoding.json

- docs/std-unicode-utf8.md
- docs/std.md
- syntax/std.go
- syntax/std_str.go
- syntax/std_unicode.go
- syntax/std_unicode_test.go
> Implement //.unicode.utf8.encode 

- rel/test_helpers.go
Improve the output generated by failed tests.
> Tidy up some assert helper logic

- rel/test_helpers.go
> Cleaner test output from AssertExprsEvalToSameValue

- rel/value.go
- rel/value_set_dict.go
- rel/value_set_dict_test.go
- Implement Dict.Less method
Checklist:
Turns out testing this is hard due to other problems #33.
> Implement Dict.Less

- rel/test_helpers.go
- rel/value_set_dict.go
- syntax/expr_set_test.go
- syntax/expr_tuple_test.go
- syntax/parse.go
- syntax/parse_string_test.go
- syntax/std_str.go
> Fix incompatibility between function-calls and attribute-gets

- syntax/compile.go
> Refactor parser megaswitch into many functions

- rel/expr_offset.go
- rel/expr_offset_test.go
- syntax/compile.go
- syntax/parse.go
Fixes #119  .
- Added offset operator that offsets all types of arrays.
Checklist:
> Fixes #119, added the array offset operator

- docs/std-re.md
- docs/std.md
- rel/expr_binary.go
- syntax/std.go
- syntax/std_re.go
- syntax/std_re_test.go
Implement regular expression functions `match`, `sub` and `subf`.
Checklist:
> Implement //.re package

- docs/std-seq.md
- docs/std-str.md
- docs/std.md
- examples/grpc/grpc-proto.arrai
- rel/value_set_array.go
- syntax/compile_xstr.go
- syntax/std.go
- syntax/std_seq.go
- syntax/std_seq_test.go
- syntax/std_str.go
- syntax/std_str_test.go
//.seq.concat moved from //.str.concat
Checklist:
> //.seq.{concat,repeat}

- rel/expr_binary.go
- syntax/std_archive.go
> Better error messages

- rel/expr_indexed_seqmap.go
- rel/expr_nest.go
- rel/expr_offset.go
- rel/expr_offset_test.go
- rel/expr_seqmap.go
- rel/expr_unnest.go
- syntax/expr_indexed_seqmap_test.go
> Clarify several arrow-operator error message

- rel/expr_darrow.go
- rel/expr_dot.go
- rel/ops_rel.go
> A few more informative error messages

- docs/intro.md
> Update offset-string syntax documentation

- Makefile
- syntax/import_cache_test.go
Fixes #105
- Skip asserting fetch duration importcache test. 
Checklist:
> Skip asserting fetch duration importcache test.

- syntax/compile.go
> Appease linter

- README.md
- cmd/arrai/shell.go
- cmd/arrai/shell_cmd.go
- cmd/arrai/shell_cmd_test.go
- rel/scope.go
- syntax/eval.go
part of #163  .
- Add `/set` and `/unset` command in interactive shell
- Some required refactoring to implement commands
- Add `Without` for scope
- Add documentation
Checklist:
> interactive shell commands

- go.mod
- go.sum
> go.{mod.sum} auto update

- README.md
- docs/tutorial/README.md
- docs/tutorial/shell.md
> Arr.ai shell tutorial

- docs/tutorial/README.md
- docs/tutorial/binding.md
> Name-binding tutorial

- cmd/arrai/shell.go
Added an error check in the interactive shell
> add error check in interactive shell

- cmd/arrai/shell.go
Fixes #210.
- Suppresses ^@, ^O, ^Q, ^V and ^Z, all of which cause strange behaviour if accidentally type into the shell command line.
Checklist:
> ai: Suppress harmful control codes

- cmd/arrai/shell.go
Fixes #211.
- Catch and report panics when evaluation exprs in `ai`
Checklist:
> ai: Handle panics gracefully

- cmd/arrai/shell.go
> Ctrl-C cancels multiline input

- docs/std-test.md
- docs/std.md
- docs/tutorial/README.md
- docs/tutorial/testing.md
- rel/expr.go
- rel/expr_binary.go
- rel/expr_set.go
- rel/value_set_native_expr_func.go
- rel/value_set_native_func.go
- syntax/std_tst.go
- syntax/std_tst_test.go
- Implement a rudimentary testing framework
Checklist:
> Rudimentary testing framework

- docs/tutorial/README.md
> Un-TODO Writing tests reference in tutorial README

- README.md
- docs/README.md
- Add references to the standard library docs in appropriate places.
Checklist:
> Refer to stdlib

- rel/value_set_generic.go
> Remove obsolete comment-out code

- rel/expr_binary.go
> Trap and context-wrap panic in BinExpr.Eval

- internal/shell/shell_completion.go
- internal/shell/shell_test.go
This commit allows this scenario
```
@> (abc: 1, abd: 2, b: 3).a<tab>
.abc   .abd
@> {'abc': 1, 'abd': 2, 'b': 3}('ab<tab>
('abc') ('abd')
```
Issue:
- While the regex is quite strict in trimming characters, it does not handle all cases of overlapping.
- It is very strict in its quotation marks, for example, using the above scenario
```
@> {'abc': 1, 'abd': 2, 'b': 3}("ab<tab>
```
the use of double quote makes the filtering fail as the predictions only use single quotes
Checklist:
> allow prefix-filtered predictions

- syntax/expr_reduce_test.go
> Fix badly named globals

- syntax/expr_set_special_test.go
> Reinstate renamed test file

- cmd/arrai/main.go
- syntax/std_os.go
- syntax/std_os_nonwasm.go
> Fix //os.args when run cmd omitted

- README.md
> Document Go 1.14 dependency

- rel/value_repr.go
- rel/value_set_array.go
- syntax/expr_set_special_test.go
> Support sparse arrays

- README.md
- docs/README.md
- docs/expr-str.md
- docs/tutorial/values.md
> Values tut tidy up

- rel/expr_array_item_entry.go
- rel/expr_binary.go
- rel/expr_dot.go
- rel/expr_offset.go
- rel/expr_reduce.go
- rel/expr_string_char_entry.go
- syntax/package_test.go
- syntax/std_bits_test.go
- syntax/std_encoding_json_test.go
- syntax/std_eval_test.go
- syntax/std_seq_test.go
- syntax/std_str_test.go
- syntax/std_test.go
> Convert some Eval panics to errors

- docs/README.md
- rel/expr_binary.go
- rel/expr_dot.go
- rel/expr_safe_tail.go
- rel/value.go
- syntax/arrai.wbnf
- syntax/compile.go
- syntax/expr_safe_tail_test.go
- syntax/parser.go
Fixes #285 .
- Adds conditional accessor syntax (look at #285 for more details)
Checklist:
> Fix #285, add conditional accessor syntax

- cmd/arrai/eval_test.go
- docs/README.md
- rel/expr_bytes.go
- syntax/arrai.wbnf
- syntax/compile.go
- syntax/expr_bytes_test.go
- syntax/parser.go
- syntax/std_seq_join_test.go
- Add Byte Array syntax
Checklist:
> Fix #257, add Byte Array syntax

- docs/README.md
- docs/std-os.md
- docs/std-unicode-utf8.md
- syntax/std_encoding_json_test.go
- syntax/std_os_test.go
- syntax/std_seq_contains_test.go
- syntax/std_seq_join_test.go
- syntax/std_seq_prefix_test.go
- syntax/std_seq_split_test.go
- syntax/std_seq_sub_test.go
- syntax/std_seq_suffix_test.go
- syntax/std_unicode_test.go
Fixes #257 .
- updated the docs with the byte array syntax
Checklist:
> fix #257, updated documentations

- rel/expr_array.go
- rel/expr_arrow.go
- rel/expr_binary.go
- rel/expr_cond.go
- rel/expr_cond_control_var.go
- rel/expr_cond_pattern_control_var.go
- rel/expr_darrow.go
- rel/expr_ident.go
- rel/expr_seqmap.go
- rel/expr_tuplemap.go
- rel/pattern.go
- rel/value_number.go
- rel/value_set_array.go
- rel/value_set_closure.go
- syntax/arrai.wbnf
- syntax/compile.go
- syntax/expr_cond_test.go
- syntax/parser.go
> Expr pattern

- rel/value_set_array.go
- syntax/expr_set_array_test.go
- syntax/expr_set_special_test.go
> Better handling of arrays with holes

- syntax/std_re.go
- syntax/std_re_test.go
> //re returns holey arrays for missing submatches

- syntax/compile.go
There are still a couple of compilation process during expr safe tail evaluation. This commit removes it.
Checklist:
> remove more compilation in evaluation in expr safe tail

- rel/value_set_array.go
- rel/value_set_array_test.go
> Fix bug in offset array Where method

- rel/expr_cond_pattern_control_var.go
- syntax/expr_cond_test.go
> Fix scoping for control-var cond

- docs/example.md
Fixes # .
- Updated document example.
Checklist:
> Updated doc example.

- .github/workflows/generate-tag.yml
Fixes #352 .
- auto-bump minor version
Checklist:
> Fix #352, auto-bump minor version

- docs/std-seq.md
- rel/value_set_array.go
- syntax/std_seq.go
- syntax/std_seq_array_helper.go
- syntax/std_seq_prefix_test.go
- syntax/std_seq_suffix_test.go
- syntax/std_str.go
> //seq.trim_{prefix,suffix}

- cmd/arrai/run.go
- error appears after running a file before dropping into debugger shell
Checklist:
> error appears after running a file before dropping into debugger shell

- rel/value_set_array.go
- syntax/expr_set_array_test.go
> Fix Array.Less slice out of bounds

- rel/expr.go
- rel/expr_dot.go
- syntax/compile.go
> fixes MissingAttrError blocking the debugger shell

- rel/pattern.go
- syntax/expr_cond_test.go
Fixes #365 .
- #365 fixed issues couldn't get value in dict or tuple patterns.
Checklist:
> Fixed issues couldn't get value in dict or tuple patterns.

- cmd/arrai/main.go
- go.mod
- go.sum
- add terminal checks before dropping into shell
Checklist:
> add terminal checks before dropping into shell

- docs/tutorial/shell.md
- internal/shell/shell.go
- internal/shell/shell_test.go
- Changes local scope name from `@locals` to `@` in the debug shell
Checklist:
> changed @locals to @ in the debug shell

- syntax/arrai.wbnf
- syntax/parser.go
- Allow more comments in the grammar
Checklist:
> allow more comments in the grammar

- rel/expr_seqmap.go
- rel/expr_seqmap_test.go
WIP #356.
- Add a basic test for SequenceMapExpr which previously had none.
Checklist:
> Add simple test for SequenceMapExp

- rel/value_repr.go
> Format byte using valid arr.ai syntax in shell

- docs/expr-str.md
- syntax/arrai.wbnf
- syntax/expr_arrow_test.go
- syntax/parser.go
> Misc minor syntax fixes

- syntax/package_test.go
> Fix dirty go.mod after running import tests

- .gitattributes
> Treat go.sum as generated code

- syntax/package_test.go
> Fix bug using tempdir for module tests

- internal/shell/shell_completion.go
- internal/shell/shell_test.go
- rel/expr_array.go
- rel/expr_bytes.go
- rel/expr_dict.go
- rel/expr_expr.go
- rel/expr_ident.go
- rel/expr_literal.go
- rel/expr_recursion.go
- rel/expr_set.go
- rel/expr_tuple.go
- rel/pattern_dict.go
- rel/pattern_expr.go
- rel/pattern_tuple.go
- rel/value.go
- rel/value_set_func.go
- syntax/arrai.wbnf
- syntax/compile.go
- syntax/compile_scanner_test.go
- syntax/compile_xstr.go
- syntax/parse_value_test.go
- syntax/parser.go
- syntax/std.go
Fixes # .
- Fix source context for most expr forms and values.
- 
Checklist:
> Fix expr source context

- syntax/import_cache_test.go
> Comment out flaky test

- rel/expr_nary.go
- syntax/compile.go
> Replace some type-assertion panics with error returns

- docs/tutorial/binding.md
- syntax/arrai.wbnf
- syntax/compile.go
- syntax/expr_fn_test.go
- syntax/expr_let_test.go
- syntax/parser.go
Fixes #435.
- Support pattern in fn
Checklist:
> Support pattern in fn

- internal/shell/shell.go
- internal/shell/shell_cmd.go
- internal/shell/shell_completion.go
- internal/shell/shell_test.go
Adds the shell inbuilts to the command prediction
> Add shell commands to the predictions

- Makefile
- cmd/arrai/info.go
Fixes #246  .
- Updated makefile to add build information to arrai binary file
- 
Checklist:
> Version flag makefile changes

- rel/expr_recursion.go
- rel/pattern_expr.go
- rel/pattern_set.go
- syntax/compile.go
- syntax/expr_let_test.go
- syntax/expr_recursion_test.go
- syntax/grammar_test.go
> Swap ident expr ident pattern patch

- rel/value_repr.go
- rel/value_set_closure.go
- syntax/expr_recursion_test.go
- add `reprClosure`
Checklist:
> add reprClosure

- syntax/arrai.wbnf
Fixes #492.
- Update arrai.wbnf parity with parser.go
> Fix arrai.wbnf

- docs/std-encoding.md
- syntax/pb_test.go
- syntax/std_encoding.go
- translate/pb/pb_decoder_entry.go
Fixes #496  .
- There is some implementation can be discussed or changed still, but the API signature and flow changes are made sure and can be released. 
- 
Checklist:
> Protobuf import changes

- cmd/arrai/sync_xlsx.go
> Fix linter diagnostic

- rel/value.go
- syntax/expr_safe_tail_test.go
> Show input for call lookup failure

- syntax/expr_join_test.go
> Join tests

- README.md
- docs/README.md
> Integrate eval.md into other docs

- rel/expr_binary.go
- syntax/expr_binary_test.go
> Fix +> to support empty dicts

- Makefile
- generate.go
- syntax/std_fmt_test.go
> Tidy up Makefile and an import

- rel/value_set_bytes.go
- rel/value_set_str.go
Fixes #555 
- Support sparse strings
- 
Checklist:
> Sparse strings

- docs/tutorial/relops.md
> Extend join tutorial

- cmd/arrai/eval.go
> More meaningful error when --out value not a dict

- syntax/std_str.go
- tools/value_util.go
> Format bytes as utf-8 encoded strings in expr-strings

- syntax/compile.go
- syntax/expr_import.go
- syntax/import.go
- syntax/import_cache.go
- syntax/import_cache_test.go
- syntax/package_test.go
- syntax/std_runtime.go
- syntax/test_helpers.go
-  imports are lazily evaluated
- 
Checklist:
> imported expressions are lazily evaluated

- docs/tutorial/comparison.md
> Update docs for set comparisons

- rel/expr_cond_pattern_control_var.go
- rel/expr_nary.go
- rel/expr_rel.go
- rel/pattern_expr_pair.go
- syntax/compile.go
- syntax/expr_array_test.go
- syntax/expr_cond_test.go
- syntax/expr_recursion_test.go
- syntax/test_helpers.go
> Fix filter pred

- rel/expr_rel.go
- rel/ops_rel.go
- rel/ops_rel_join_test.go
> Don't squash panics in join operators

- rel/value_set_bytes.go
- rel/value_set_str.go
> Remove some unnecessary mallocs

- go.mod
- go.sum
> Latest frozen for reduced GC pressure

- cmd/arrai/main.go
> Fix profile cmdline parsing

- cmd/arrai/eval.go
- cmd/arrai/run.go
- pkg/arrai/out.go
- pkg/output/out.go
This function is moved into its own package so arr.ai binaries can import this function
> move handleEvalOut to its own package
