rel/expr_tuple.go
rel/set_test.go
rel/tuple_test.go
rel/value_set.go
rel/value_tuple.go
syntax/lex.go
syntax/parse.go
tests/expr_binary_test.go
tests/expr_reduce_test.go
tests/expr_unary_test.go
tests/parse_expr_test.go
tests/parse_value_test.go

This PR changes the syntax for tuples and sets. These collection types now conforms to the intended spec.
* Sets: `{}`
* Tuples: `()`
* Arrays: `[]`
Use of `()` for tuples now clashes with the classical use of parens to wrap expressions. This PR includes a hack workaround to continue supporting `(<expr>)`.
Includes:
* Syntax parse changes
* `String()` methods for output
* Hopefully does not break `(<expr>)`.
* Updated tests related to the syntax changes and `String()` methods.
No new tests have been added

Array tuple set syntax

---

cmd/arrai/json.go
cmd/arrai/main.go
translate/json.go
translate/json_test.go

This PR adds a json translation command to arrai.
Usage:
```bash
$ echo '<json blob>' | arrai json
```
This functionality is also available in code through the `translate` package
```go
val, err := translate.JSONToArrai(data interface{})
```
Assumes raw json has already been marshalled into an interface. Will error out if `data` is a strongly typed struct (or anything that doesn't come out of `json.Unmarshal()` on a blank interface variable)

Json translator

---

cmd/arrai/json.go
cmd/arrai/main.go
rel/expr_binary.go
tests/expr_binary_test.go
translate/json.go
translate/json_test.go

Fix for binary relations where the _key_ is a string. Allows
```go
{|@,@item| |"a","b"|, |"c","d"|}("a") // == "b"
```
Only from commit 42100be onwards

Map function call fix

---

README.md
go.mod
go.sum

**Issue** 
When installing `arrai`, The version of wbnf was older that was failing the build
This is the output from terminal
```shell script
$ GO111MODULE=on go install github.com/arr-ai/arrai/cmd/arrai
go: finding github.com/arr-ai/arrai/cmd/arrai latest
go: finding github.com/arr-ai/arrai latest
go: finding github.com/arr-ai/arrai/cmd latest
go: extracting github.com/arr-ai/arrai v0.0.0-20200112125929-3fcea2304631
go: extracting github.com/arr-ai/proto v0.0.0-20180422074755-2ffbedebee50
go: extracting github.com/arr-ai/wbnf v0.0.0-20200110014938-ba95372c7523
go: extracting github.com/arr-ai/frozen v0.6.0
go: extracting github.com/arr-ai/hash v0.4.0
../pkg/mod/github.com/arr-ai/arrai@v0.0.0-20200112125929-3fcea2304631/rel/node_to_value.go:15:61: p.Singletons undefined (type …
```

Updating the wbnf version and updating README

---

.github/workflows/wasm.yml

Fixes #49
- Adds `wasm.yml` to github workflows that builds a wasm binary:
`GOOS=js GOARCH=wasm go build -o arrai.wasm ./cmd/arrai`
- Then the binary is executed with node:
`node wasm_exec.js arrai.wasm`
This is quite preliminary in terms of testing, but any linking errors or compile errors will fail the ci
NOTE:
the line: 
`curl -O https://raw.githubusercontent.com/golang/go/46f9aea80197bfdf4c024c3f5a71be51a2facf59/misc/wasm/wasm_exec.js`
goes and gets the wasm_exec.js from the version of go that is 1.14; (couldn't fun out how to get it from the local go installation)
Checklist:
- [] Made corresponding changes to the documentation

Add wasm workflow

---

docs/std-os.md
syntax/std.go
syntax/std_os.go
syntax/std_os_nonwasm.go
syntax/std_os_wasm.go
syntax/util.go

- Add basic `os` and `file` functions
- `cwd`
- `file`
- `pathSeparator`
- `pathListSeparator`
- `args`
- `getenv`

add basic os and file stdlib

---

syntax/std_os.go
syntax/std_os_nonwasm.go
syntax/std_os_wasm.go

Fixes issue mentioned from the [comment](https://github.com/arr-ai/arrai/issues/60#issuecomment-596186873)  .
- Add wasm safe build for `//.os.file`

wasm safe //.os.file

---

rel/expr_binary.go
rel/expr_dot.go
rel/expr_if_else.go
rel/expr_logical.go
rel/expr_reduce.go
rel/expr_unary.go
rel/names.go
rel/number_test.go
rel/set_test.go
rel/tuple_test.go
rel/value.go
rel/value_number.go
rel/value_set.go
rel/value_set_bytes.go
rel/value_set_closure.go
rel/value_set_dict.go
rel/value_set_eclosure.go
rel/value_set_func.go
rel/value_set_native_func.go
rel/value_set_str.go
rel/value_tuple.go
syntax/std_str.go

Fixes #40.
- Rename Value.Bool() to Value.IsTrue() to improve readability when testing. `if v.IsTrue()` reads more naturally than `if v.Bool()`.

Rename Value.Bool() to Value.IsTrue().

---

docs/std-eval.md
docs/std-os.md
docs/std.md
rel/test_helpers.go
syntax/std.go
syntax/std_test.go
syntax/test_helpers.go

- Implement `//.tuple` to convert dictionaries to tuples.
- Implement `//.dict` to convert tuples to dictionaries.
Checklist:

//.tuple and //.dict

---

docs/intro.md
go.mod
go.sum
syntax/expr_tuple_test.go
syntax/parse.go

> **Reviewer note:** Only the final commit is relevant.
- Allow attribute access to use string syntax, e.g. `('-x': 42)."-x"`. Empty names too: `('': 42).''`.
Checklist:

Allow string syntax for get attribute

---

cmd/arrai/eval.go
cmd/arrai/eval_test.go
docs/intro.md
go.sum
rel/astnode_value.go
rel/expr_darrow.go
rel/expr_tuple.go
rel/json.go
rel/ops_set.go
rel/test_helpers.go
rel/value_repr.go
rel/value_repr_test.go
rel/value_set_dict.go
rel/value_set_generic.go
rel/value_tuple.go
syntax/expr_set_test.go
syntax/parse.go
syntax/parse_string.go
syntax/std_str.go
syntax/test_helpers.go

Strings (including the empty set) print bare.
Everything else prints as a valid arr.ai value.
Fixes #75.
- Print strings as bare text. Treat empty set as empty string.
- Print everything else as a valid arr.ai value.
- Fix tuple expr canonicalization.
Checklist:

Eval output

---

syntax/std.go
syntax/std_json.go
syntax/std_json_test.go
syntax/std_str.go
translate/json.go
translate/json_test.go

JSON Mapping
Maps JSON values to arrai objects
- `42` -> `42`
- `true/false` -> `(b: true/false)`
- `null` -> `(null: {})` 
- `"abc"` -> `(s: "abc")`
- `[1, 2, 3]` -> `(a: [1, 2, 3])`
- `{"a": 42}` -> `{"a": 42}`
Checklist:

JSON to arrai object

---

docs/std-os.md
rel/expr_dot.go
rel/value_set_bytes.go
rel/value_set_generic.go
rel/value_set_native_func.go
rel/value_set_str.go
rel/value_tuple.go
rel/value_tuple_bytes_byte.go
rel/value_tuple_bytes_byte_test.go
rel/value_tuple_str_char.go
rel/value_tuple_str_char_test.go
syntax/std_os.go
syntax/std_os_nonwasm.go
syntax/std_os_test.go
syntax/std_os_wasm.go

When accessed, `//.os.stdin` reads stdin into a byte array.
Checklist:

Implement //.os.stdin

---

syntax/std_encoding_json.go
syntax/std_encoding_json_test.go

Checklist:
Don't yet have a way to express byte arrays easily, so testing will be added later #97.

Handle Bytes in //.json.decode

---

examples/json/foo.json
syntax/package_test.go
syntax/parse.go

Fixes #65  .
- syntax parse update grammar for local package to include file extension 
- change way to walk through the ast tree in local package
Checklist:

Add import for json format(#65)

---

docs/intro.md
syntax/compile.go
syntax/expr_tuple_test.go
syntax/parse.go

- Support unnamed tuple attributes, e.g.: `(:x, :t.y)`.
Checklist:

Implicitly named attrs

---

docs/std-net.md
syntax/std.go
syntax/std_net.go
syntax/std_net_test.go

- Add basic `//.net.http.get` and test 
- Add documentation
Checklist:

add //.net.http.get and documentation

---

docs/expr-str.md
syntax/compile.go
syntax/compile_xstr.go
syntax/parse_string_test.go

The following expression string:
```
$"
${[1, 2, 3] >> $"
${.}
.
"::\n}
"
```
produces the following output:
```
"1
.
2
.
3
.
"
```
which is as intended. However, a common styling convention is to indent the closing line of a multiline construct at the same level as the open line:
```
$"
${[1, 2, 3] >> $"
${.}
.
"::\n}
"`)
```
However, the output now changes to include the spaces on the last line, which was almost certainly not the intent:
```
"1
.
2
.
3
.
"
```
This PR trims pure trailing white space after the last newline.
Checklist:

Trim pure whitespace at the end of expression strings.

---

syntax/compile.go
syntax/package_test.go
syntax/parse.go

- Reinterpret `//./a.b` as equivalent to `(//./a).b` (currently equivalent to`//./'a.b'`.
- Consequently, importing files with extensions will require string-name syntax: `//./'a.b'`.
Checklist:

Tidy up import path syntax

---

.github/workflows/go.yml

- Removes dependency of `build` job on [lint, test], thus allowing faster CI completion.
- 
Checklist:

Parallelise workflow build job

---

rel/value_set_array.go
rel/value_set_generic.go
syntax/std_str.go

- Rework `AsArray` to be more efficient by assuming an array-like `Set` is always an `Array`.
- Keep original `AsArray` as `asArray` for internal use.
Checklist:
- [n/a] Added related tests (existing)
- [n/a] Made corresponding changes to the documentation (no language change)

Cleaner array detection and usage

---

rel/value_tuple_dict_entry.go

A fix to use the `Equal` method to compare the keys in dictionary entry tuple

fix compare dict entry tuple key

---

rel/value_set_array.go
rel/value_set_bytes.go
rel/value_set_str.go

the index method will not allow returning `len(array.values)`, it affects appending values to the array. This change will allow that.

fix index method of Array, String, and Bytes

---

cmd/arrai/shell.go
cmd/arrai/shell_test.go

Part of #163.
- Allow multiline expression in arrai interactive shell
Current problem:
There's no way to get out of multiline mode. You have to make a balanced expression.
Checklist:

allow multiline expression in arrai interactive shell

---

cmd/arrai/shell.go
cmd/arrai/shell_test.go

initially to check if a line ends in an argument `\a \b`, it checks
with the regex `\\.+$` which fails on cases like
```
let f = \x \y x + y; f(3, 4)
```
Checklist:

fix multiline balance check for arrai argument

---

cmd/arrai/shell.go

Now multiline prompts look like this
```bash
@> let a = 42;
> let b = 54;
> a + b
```

replaced multiline prompt to ' > '

---

docs/std-rel.md
examples/grpc/grpc-proto.arrai
syntax/std_rel.go
syntax/std_rel_test.go

Fixes #188  .
- `//rel.union` can now take an array of sets or set of sets
Checklist:

Fix #188, //rel.union accepts set of sets

---

cmd/arrai/shell.go

Fixes stdlib completion in arrai interactive shell. It no longer needs `//.` to begin prediction.

stdlib completion in arrai interactive shell

---

README.md
cmd/arrai/file_util.go
cmd/arrai/file_util_test.go
cmd/arrai/main.go

Fixes #199 .
- you can run arrai script by doing the command `arrai path/to/file.arrai`
Checklist:

Fix #199, add command `arrai file.arrai`

---

docs/std-bits.md
docs/std.md
syntax/std.go
syntax/std_bits.go
syntax/std_bits_test.go

Fixes #203  .
- Add `//bits.mask` and `//bits.set`
Checklist:

Fix #203, add bitmask and intset functions to stdlib

---

rel/value_repr.go

Fixes #204  .
- `{()}` now is printed as `true`

Fix #204, {()} always print true

---

cmd/arrai/shell.go
cmd/arrai/shell_test.go

- Initially completion relies on a line beginning with `//` to check
if it is trying to access stdlib. This commit allows getting the
last token and do a completion based on that token. It allows
completion in the middle of an expression.
Checklist:

enable stdlib completion in the middle of an expression

---

syntax/arrai.wbnf
syntax/expr_set_with_without_test.go
syntax/parser.go

Fixes #177.
- Swap `with` and `without` in parser so that `with` doesn't suppress `without` under PEG semantics.
Checklist:

Fix without operator

---

Makefile
rel/test_helpers.go
rel/value_set_native_func.go
syntax/std.go
syntax/std_tst.go

- `make install` installs arrai and creates symlinks `ai` and `ax`.
Checklist:
- Currently, there are no install-from-source instructions

make install arrai, ai and ax

---

cmd/arrai/shell.go
cmd/arrai/shell_test.go

Allows backtick escape
Checklist:

fix `` escape in shell

---

cmd/arrai/shell.go
cmd/arrai/shell_test.go

Fixes #213 .
- string escape isn't considered as an argument
Checklist:

fix #213, string escape no longer triggers multiline mode

---

internal/shell/shell.go
internal/shell/shell_completion.go
internal/shell/shell_test.go

- This commit allows tab completion on tuples and dictionaries that are currently being typed on
- Moved some of the completion code into `shell_completion.go`
It allows these cases:
```
(a: 1)<tab>
(a: 1).<tab>
{"a": 1}<tab>
{"a": 1}(<tab>
```
TODO:
- move shell completion test to `shell_completion_test.go`
- prefix based completion
Checklist:

tab completion on tuples and dictionaries that are currently typed

---

internal/shell/shell.go
internal/shell/shell_test.go

increments in `appendLine` wasn't reset every loop, this commit resets it which allows cases such as
```
"\"x"
```
Checklist:

fixes multiline string with escapes

---

internal/shell/shell_completion.go
internal/shell/shell_test.go

//TODO this is a quick fix, a better trimming function is needed
This allows predictions to work when the possible predictions have shared prefixes of either `"`, `'`, or `
Checklist:

fix autocomplete when predictions have shared quote prefixes

---

rel/pattern.go
syntax/expr_let_test.go

- handle duplicated tuple pattern name
- two sides of tuples in let statement must be the same name:expr

handle duplicated tuple pattern name

---

syntax/compile.go

Worst case, falls back to the current behaviour of highlighting just the operator if merging Scanners fails.
Checklist:

Expand unop and binop source to include args

---

docs/tutorial/comparison.md
syntax/compile.go
syntax/expr_member_test.go

Implement !<: operator

---

docs/std-encoding.md
syntax/std_encoding_json_test.go
translate/translator.go
translate/translator_json_test.go
translate/translator_yaml_test.go

Currently, `null` encodes to `(null: {})`. But, since nothing else currently encode to the empty tuple, this change uses
Checklist:

Decode JSON null as empty tuple

---

syntax/compile.go
syntax/expr_let_test.go

- support tuple construction shortcut in pattern matching
Checklist:

support tuple construction shortcut in pattern matching

---

syntax/compile.go

now error message will have filename in it, relative to current directory. For example:
```
arrai/examples/grpc/grpc-proto.arrai:2:16:
\app
let grpc = //{./grp}; [recovered]
panic: open arrai/examples/grpc/grp.arrai: no such file or directory
```
Checklist:

error report now has filepath relative to current directory

---

rel/pattern.go
rel/value_number.go
syntax/compile.go
syntax/expr_let_test.go

Fixes #237.
- support dict pattern `let {"x": a, "y": b} = {"x": 4, "y": 5}; [a, b]`
Checklist:

support dict pattern

---

Makefile

Some package tests in package_test.go seems to run a go get a command
which pollutes the go.mod and go.sum for every make test. This commit
fixes it by adding a go mod tidy command in the make test script.

Fixes #290, add go mod tidy after a test in Makefile

---

internal/shell/shell_completion.go
internal/shell/shell_test.go

- Allows stdlib completion without `.`
```
@> //str<tab>
contains   expand     has_prefix has_suffix join       lower      repr       split      sub        title      upper
```
Checklist:

allows stdlib completion without "." at the end

---

rel/expr_binary.go
rel/expr_dot.go
rel/expr_reduce.go
rel/expr_unary.go
rel/value.go
rel/value_set_array.go
rel/value_set_array_test.go
rel/value_set_bytes.go
rel/value_set_closure.go
rel/value_set_dict.go
rel/value_set_dict_test.go
rel/value_set_eclosure.go
rel/value_set_func.go
rel/value_set_generic.go
rel/value_set_native_expr_func.go
rel/value_set_native_func.go
rel/value_set_str.go
rel/value_set_str_test.go
rel/value_set_test.go
rel/value_test.go
rel/value_tuple_bytes_byte_test.go
syntax/std_tst.go
syntax/std_tst_test.go

This PR adds `CallAll` to the interface `Set`
`CallAll(arg)` works on `Tuple`s inside `Set` which have the `@` attribute. It finds any tuple whose `@` attribute matches `arg` and return the corresponding values in a `Set`. If there are no corresponding values, it returns an empty `Set`.
Checklist:

add CallAll to Set interface

---

rel/expr.go
rel/expr_arrow.go
rel/expr_darrow.go
rel/expr_seqmap.go
rel/expr_tuplemap.go
syntax/expr_let_test.go

Panics from pattern matching failures weren't being trapped and turned into arr.ai stack frames.

Report arr.ai stack traces when pattern matching fails

---

rel/pattern.go
syntax/expr_let_test.go

Fixes #324 .
- `let [[x]] = []` fails
Checklist:

fix nested empty array pattern value

---

internal/shell/shell.go

- Only allowing character escapes in strings in arrai shell

restricting escapes to only happen in strings in arrai interactive shell

---

rel/expr_binary.go
rel/expr_dot.go
rel/expr_safe_tail.go
rel/value.go
syntax/compile.go
syntax/expr_safe_tail_test.go

Initial implementation compiles the chain of accessors during evaluation. This makes sure compilation happens before.
Checklist:

reimplement conditional accessor syntax

---

docs/README.md
rel/expr_array.go
syntax/arrai.wbnf
syntax/compile.go
syntax/expr_let_test.go
syntax/expr_set_array_test.go
syntax/parser.go

Fixes #338 .
- Add syntax for sparse array
```
[1, 2, , 3, , 4]
```
Checklist:

Fixes #338, add syntax for sparse array

---

docs/README.md
rel/expr_recursion.go
syntax/arrai.wbnf
syntax/compile.go
syntax/expr_recursion_test.go
syntax/parser.go
syntax/std.go

Fixes #14.
- Implement syntactic sugar for recursive functions
Checklist:

Fixes #14, implement syntactic sugar for recursive functions

---

docs/tutorial/binding.md
syntax/arrai.wbnf
syntax/compile.go
syntax/expr_arrow_test.go
syntax/parser.go

Fixes #253 .
- Support function parameters in pattern matching
```
@> 1 -> \x let [(x), y] = [1, 2]; y   # Should pass
@> [1, 2] -> \[x, y] x + y            # Should pass.
```
Checklist:

support pattern matching in function parameters

---

syntax/std_os_nonwasm.go

Fixes #375 .
- `//os.args` doesn't handle running arrai script from syntax library, this PR handles that
Checklist:

fixes #375, handles running arrai script from syntax lib

---

docs/std-eval.md
syntax/std_eval.go
syntax/std_eval_test.go

- allows `//eval.value` to take in string and an array of bytes
Checklist:

allows `//eval.value` to take in an array of bytes

---

docs/example.md
examples/grpc/grpc.arrai
rel/expr_cond_pattern_control_var.go
rel/expr_pattern.go
rel/pattern.go
syntax/arrai.wbnf
syntax/compile.go
syntax/expr_cond_test.go
syntax/parser.go

Fixes #371 .
- Changed cond syntax to `cond x {...}`
Checklist:

Cond change to `cond x {...}`

---

syntax/compile.go
syntax/scanners_test.go

Before, when an access operation fails, the stack dump only show its arguments or attribute access is highlighted. This commit extends the highlighting up to the accessed value.
before
```
a.b.<highlighted>c</highlighted>
```
after
```
<highlighted>a.b.c</highlighted>
```
Checklist:

expands the highlighted source context for access operations

---

syntax/arrai.wbnf
syntax/compile.go
syntax/expr_arrow_test.go
syntax/parser.go

Fixes # .
- When `.` is in scope, `=> expr` is equivalent to `. => expr`. Same for `>>` and `:>`.
- 
Checklist:
- Already documented

Implement unary =>, >> and :>

---

syntax/arrai.wbnf
syntax/parser.go

Fixes # .
- Currently, `a.b?:{} => ... >> ...` parses as `a.b?:({} => ... >> ...)`, which is counterintuitive.
The expectation is that `?:` bind quite tightly, so only the `{}` is picked up as the fallback value. This is because the most common case for the `?:` fallback value is a simple "zero"-value like `0`, `[]`, `""`, etc.
Checklist:

Change optional fallback from expr to atom

---

internal/shell/shell_completion.go
internal/shell/shell_test.go

- Adds tab completion on global variables
- Fixes this scenario
```
(a: 1).  <tab>
```
Before `.a` will be suggested, now it doesn't and it will instead look for global variables.
Checklist:

tab completion on global variables in arrai shell

---

cmd/arrai/main.go

- Add `-d` flag and also env var `ARRAI_DEBUG` to drop into debug shell
Checklist:

add debug flag to drop into the debug shell

---

rel/expr_array.go
rel/value_set_array.go
rel/value_set_array_test.go
syntax/expr_array_test.go
syntax/expr_seqmap_test.go

Fixes #356 .
- Simplify creating array from set to account for holes, which were not accounted for.
- Fix an incidental panic when trying to stringify an array with holes.
New algorithm needs to loop through the set twice, once to get the index bounds of its elements, then again to populate the []Value array.
Checklist:

Fix #356: set to array with holes

---

rel/expr_recursion.go
rel/pattern_expr.go
rel/pattern_set.go
syntax/grammar_test.go
syntax/parse.go

- This is a quick hack to support the base case of `let g = {:...some grammar...:}` (#398).
Checklist:

Support grammars in let-bindings

---

docs/tutorial/binding.md
rel/pattern_expr.go
rel/value_set_generic.go
syntax/expr_let_test.go

Fixes #325 .
Fixes #254 .
- Support `True` and `False` in pattern matching
- Support arbitrary expressions e.g. `(1+2)`, `"hello"`
Checklist:

Support arbitrary expressions in pattern matching

---

cmd/arrai/command_util.go
cmd/arrai/command_util_test.go
cmd/arrai/main.go

Fixes #401.
- Allows the use of global flags in the command `arrai file.arrai` 
For context, I built this feature where user can do the command `arrai file.arrai`. The trick was to transform the command internally to `arrai run file.arrai`. But yesterday's feature, the debug flag, messed that up, this PR will handle any global flags in the future, so user can do `arrai -d --any-other-flag file.arrai` and have it translated to `arrai -d --any-other-flag run file.arrai`
Checklist:

Fixes #401, allows arrai -d path/to/file.arrai

---

docs/README.md
syntax/arrai.wbnf
syntax/expr_bytes_test.go
syntax/parser.go

- The more complicated expressions in byte expr will now have to enclosed in parentheses to avoid parsing error
Initially, this was parsed wrongly
```
<< expr >> => transform(.)
```
This commit will require it to be
```
<< (expr) >> => transform(.)
```
Checklist:

enclosed expr in byte expr with parentheses in the grammar

---

cmd/arrai/command_util_test.go
cmd/arrai/eval_test.go
cmd/arrai/run_test.go
go.mod
go.sum
rel/astnode_value_test.go
rel/value_number_test.go
rel/value_set_array_test.go
rel/value_set_dict_test.go
rel/value_set_str_test.go
syntax/expr_array_test.go
syntax/expr_arrow_test.go
syntax/expr_cond_test.go
syntax/expr_dot_test.go
syntax/expr_literal_test.go
syntax/expr_member_test.go
syntax/expr_order_test.go
syntax/expr_rel_test.go
syntax/expr_set_array_test.go
syntax/expr_set_compare_test.go
syntax/expr_set_special_test.go
syntax/expr_set_with_without_test.go
syntax/expr_tuple_test.go
syntax/grammar_test.go
syntax/import_cache_test.go
syntax/package_test.go
syntax/scanners_test.go
syntax/std_re_test.go
syntax/std_seq_sub_test.go

- Parallelise as many tests as possible
- Use wbnf v0.18.0, which is much faster due to greatly reduced malloc overhead.
Checklist:

Much faster tests

---

docs/README.md
syntax/arrai.wbnf
syntax/compile.go
syntax/expr_tuple_test.go
syntax/parser.go

Fixes #417.
- allows syntactic sugar for recursive functions in a tuple.
Checklist:

fix #417, adds recursion syntax in tuple

---

cmd/arrai/shell.go
docs/tutorial/shell.md
internal/shell/shell.go
internal/shell/shell_cmd.go
internal/shell/shell_cmd_test.go
internal/shell/shell_test.go
internal/shell/shell_wasm.go
rel/expr.go
rel/expr_test.go

Fixes #434 .
- Stack frame navigation in arrai debug shell
When evaluation fails, it will drop into the debug shell with the last frame. This PR adds the `/up` which will change into the previous frame and replace the scope with the corresponding frame's scope. `/down` will change into the next frame.
Checklist:

fix #434, adds stack frame navigation in arrai debug shell

---

internal/shell/shell.go
internal/shell/shell_test.go

Fixes #425 .
- Allows a line to end with `.` but not all scenarios. Partial attribute access will still enter multiline mode.
Checklist:

fix #425, allows `.` at the end without entering multiline mode in ai

---

rel/value_set_closure.go
syntax/expr_fn_test.go

- `(\[x, y] 42)([1, 2, 3])` and `(\[x, y] x + y)([1, 2, 3])` should fail
Checklist:

Handle closure call error

---

syntax/std_str.go
syntax/std_str_test.go

Fix crash with holey arrays in expression strings

---

Makefile

Fixes # .
- Changed output to:
```
arrai -v
arrai DIRTY-cca2f85f92bbdcc5852d7bebe9ef20399b874f2f (~1 = v0.64.0) darwin/i386
``` 
Checklist:

Added parenthesis for number of different logs.

---

Makefile

Fixes #456 .
Changed the different logs behind HEAD from
```
$ arrai v
arrai 751a975944edadf56a2558a8a21eebcfd47fc52e (~3 = v0.123.0) darwin/amd64
```
to
```
$ arrai v
arrai 751a975944edadf56a2558a8a21eebcfd47fc52e (from v0.123.0) darwin/amd64
```
It is simple and no confusion.
Checklist:

Version for dirty repos

---

docs/tutorial/shell.md

Correct `cond` default syntax keyword, changed from `*` to `_`
Fixes # .
- Correct cond default syntax keyword, changed from * to _
- 
Checklist:

Correct `cond` default syntax keyword

---

docs/tutorial/shell.md

Correct cond sample, changed from `cond ()` to `cond {}`.
Fixes # .
- Correct `cond` sample from `cond(...)` to `cond{...}`
- 
Checklist:

Correct cond sample

---

syntax/arrai.wbnf
syntax/expr_arrow_test.go
syntax/expr_let_test.go
syntax/parser.go

Fixes #442 .
- Will pasre `(a)` in `let a = 5;(a)` to expression.
Checklist:

Fixed parenthesis enclosed expression issue  

---

docs/example.md
syntax/arrai.wbnf
syntax/compile.go
syntax/expr_filter_test.go
syntax/parser.go

Fixes #445 .
- Add filter operator `{1, [2, 3], 4, [5, 6]} filter . {[a, b]: 42}`
Checklist:

Implement filter op

---

syntax/compile.go

- Fix syntax of cond sample
It's still not a very good example, since the first case necessarily always matches
Checklist:

Fix syntax of cond sample

---

docs/tutorial/binding.md
rel/pattern_array.go
rel/pattern_dict.go
rel/pattern_fallback.go
rel/pattern_tuple.go
syntax/arrai.wbnf
syntax/compile.go
syntax/expr_let_test.go
syntax/parser.go

Fixes #469 .
- support nested fallback in array pattern: `@> let [x, [y, ?z:0]] = [1, [2]]; [x, y, z]`
- support nested fallback in tuple pattern: `@> let (x?: (y: (k?: w:42))) = (x: (y: (z: 1))); w`
- support nested fallback in dict pattern: `@> let {"a"?: {"b": {"c"?: x:42}}} = {"a": {"b": {"k": 1}}}; x`
Checklist:

nested pattern fallback

---

README.md
docs/example.md
rel/expr_binary.go
syntax/arrai.wbnf
syntax/compile.go
syntax/expr_binary_test.go
syntax/parser.go

Fixes #133 .
- Merges two tuples and combines all rhs(right-hand side) attributes and any lhs(left-hand side) attributes whose name isn't on the rhs into a new tuple.
- 
Checklist:

Implements merge operator `+>`

---

internal/shell/shell_cmd.go
internal/shell/shell_cmd_test.go

Fixes #527 .
- set and unset cmd now use the same variable name rule as IDENT
Checklist:

fixes #527, set and unset use the same rule as IDENT

---

cmd/arrai/main.go

Without an exit error, commands like `arrai run nonexistent_file.arrai > out.txt` will produce an empty `out.txt` since the `arrai run` command is considered successful.

Exit with an error code if app.Run returns an err

---

rel/value.go
syntax/pb_test.go
translate/pb/pb_decoder.go

- Arrays output as [a, b, c] instead of `[(@:0, @item:a), (@:0, @item:b), (@:0, @item:c)]`
- Errors unpacking elements return errors instead of adding error messages to the output.
- Refactor logic for primitive types.
Checklist:

Fix protobuf import semantics

---

syntax/std_rel_test.go
syntax/test_helpers.go

Currently these assertion failures just log the difference but the test appears to pass.
It turns out `TestRelUnion` is actually failing the assertion in `master` but `make` is passing.

Log errors when asserts fail

---

cmd/arrai/eval.go
cmd/arrai/eval_test.go
cmd/arrai/run.go
cmd/arrai/run_test.go
docs/cmdline/eval.md
go.mod
go.sum
pkg/ctxfs/ctxfs.go

Partially implements #528.
- Add `--out=file:<path>` and `--out=dir:<path>` flags to `eval` and `run` commands.
Checklist:

--out modes for run and eval

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/question.md

These instructions stand out fine in the editor view, but I'd like them to be greyed out in the rendered view.
Actually, never mind. We need the warning to also stand out for people posting comments.

Use quote format for GitHub template instructions

---

rel/expr_tuple_project.go
rel/names.go
syntax/arrai.wbnf
syntax/compile.go
syntax/expr_tuple_project_test.go
syntax/parser.go

Fixes #550.
1. Allows `t.|a, b, c|` which takes attributes of `a, b, c`
2. Allows `t.~|a, b, c|` which takes all the attributes of `t` except
`a, b, c`
3. Changes `Names.String` to use `OrderedNames` for deterministic output
Checklist:

fix #550, add more concise tuple projection syntax

---

rel/expr_single_nest.go
rel/ops_rel.go
syntax/arrai.wbnf
syntax/expr_single_nest_test.go
syntax/parse.go
syntax/parser.go

Change proposed in this pull request:
- Introduce optimized single attribute nest `x nest y`
Checklist:

Optimize nest for single attribute

---

rel/expr_nest.go
rel/ops_rel.go
syntax/arrai.wbnf
syntax/expr_nest_test.go
syntax/parse.go
syntax/parser.go

Fixes #551 .
- allow `{|x, y, z| ...} nest ~|x|a` which is equivalent to `{|x, y, z| ...} nest |y, z|a` 
Checklist:

fix #551, implement attribute-set complement in nest

---

go.mod
rel/value_set_bytes.go
rel/value_set_str.go
syntax/expr_let_test.go
syntax/expr_set_compare_test.go
syntax/grammar_test.go

fixes comparison of datatypes with offset. Fixes #553 
Initially
```
@> "abc" = 2\"abc"
true
```
Checklist:

fixes comparison of datatypes with offset

---

syntax/arrai.wbnf
syntax/expr_tuple_test.go
syntax/parser.go

This PR allows
```
let (?: x:42) = (); x
```
which is a shorter form of
```
let (x?: x:42) = (); x
```
Checklist:

allow shorter form of pattern fallback in tuple

---

syntax/arrai.wbnf
syntax/expr_filter_test.go
syntax/parser.go

Previously, arrow operators couldn't appear as result exprs
Fixes # .
- 
- 
Checklist:

Fix syntax of cond exprs

---

rel/expr_dot.go
rel/expr_dot_test.go

Fixes #572.
- Add a length check for the attribute before slicing it.
Checklist:

Return the right error when accessing nonexistent empty tuple key

---

syntax/std_seq.go

Correctly report 'not a byte array' instead of 'not a string'

---

syntax/prettify.go
syntax/std_fmt_test.go

Fixes #575 .
- Use repr instead of just the string value.
Checklist:

Use repr for pretty printed strings to include offsets

---

syntax/compile_xstr.go
syntax/parse_string_test.go

initially the expression
```
$`
abc:
${[1, 2, 3] >> $`
number:
${.}
`}
`
```
would output
```
abc:
number:
1
number:
2
number:
3
```
this commit fixes that, now it outputs
```
abc:
number:
1
number:
2
number:
3
```
Checklist:

fixes indentation problem from xstr

---

syntax/compile_xstr.go
syntax/parse_string_test.go

initially the expression
```
$`
abc
${''}
def
`
```
would output
```
abc
def
```
this commit suppresses any lines which only contains computed empty string
```
abc
def
```
Checklist:

fixes extra whitespace after computed empty string

---

docs/expr-str.md
syntax/compile_xstr.go
syntax/parse_string_test.go

Initially, the expression
```
$"
stuff:
${[1, 2, 3] >> $"
letter:
"::\i}
"
```
will output:
```
stuff:
letter:
letter:
letter:
```
This is caused by the newline after the word `letter:` in the string template.
This commit removes the last whitespaces of string expression for better formatting of
multiline expression.
The output now is:
```
stuff:
letter:
letter:
letter:
```
Checklist:

strip last whitespaces in a string template

---

syntax/compile_xstr.go
syntax/parse_string_test.go

Initially, the following expr:
```
$`
root:${''}
children
`
```
will output
```
root:	children
```
This commit fixes that
```
root:
children
```
Checklist:

fixes suppression of line after empty computed string

---

syntax/std_seq.go
syntax/std_seq_sub_test.go

Fixes #588 .
- If old is non-empty and subject is empty, return subject.
Checklist:

Fix //seq.sub for string sub of empty string

---

syntax/std.go
syntax/std_test.go

Fixes #571.
- Ensure dict key is a string before converting. If empty, just use "".
Checklist:

Handle empty keys in //tuple

---

docs/std-os.md
syntax/std_os.go
syntax/std_os_nonwasm.go
syntax/std_os_test.go
syntax/std_os_wasm.go

Fixes #594.
- Add `//os.exists(filepath)` to std_os.go
Checklist:

Add //os.exists to check for existence of file or directory

---

docs/std-os.md
rel/value_set_array.go
rel/value_set_bytes.go
rel/value_set_str.go
syntax/std_os.go
syntax/std_os_nonwasm.go
syntax/std_os_test.go
syntax/std_os_wasm.go

`//os.stdin` hangs if `stdin` is a terminal, which is not always desirable. This allows scripts to behave differently depending on how the script is being run.

Add //os.isatty(fd) to allow scripts to handle //os.stdin more intelligently

---

cmd/arrai/run.go
cmd/arrai/sync_other.go
cmd/arrai/test.go
cmd/arrai/test_test.go
internal/test/test.go
pkg/ctxfs/ctxfs.go
syntax/import.go
syntax/std_os_nonwasm.go
tools/file_util.go

This PR replaces `os.File` and `ioutil.ReadFile` with `afero` to avoid direct os access.
Checklist:

replace fs access with afero

---

cmd/arrai/run_test.go
syntax/compile.go
syntax/import.go

This commit will allow nested root markers in a project.
Root markers will be found by going up the source directory
of a file. A root marker can be in the same directory or the parent
directories. The root marker locations will also be cached for faster
root marker lookup.
This commit also fixed the root marker lookup as initially it was
done by searching from the provided import path instead of the directory
location of the source scripts.
Checklist:

allow nested import root and import root fixes

---

rel/expr_tuplemap.go
rel/value.go
rel/value_set_array.go
rel/value_set_bytes.go
rel/value_set_closure.go
rel/value_set_dict.go
rel/value_set_eclosure.go
rel/value_set_generic.go
rel/value_set_native_func.go
rel/value_set_str.go
rel/value_set_test.go
rel/value_tuple.go
rel/value_tuple_array_item.go
rel/value_tuple_array_item_test.go
rel/value_tuple_bytes_byte.go
rel/value_tuple_bytes_byte_test.go
rel/value_tuple_dict_entry.go
rel/value_tuple_str_char.go
rel/value_tuple_str_char_test.go
syntax/expr_import.go

Fixes # .
- {Set,Tuple}.Map signatures changed to allow for errors to propagate normally.
- 
Checklist:

{Set,Tuple}.Map return errors

---

contrib/json.arrai

`x < {}` is the current best means of testing whether something is a number.

Improve number check
